config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token

from hasker.contrib.qa.views import QuestionsListView

urlpatterns = [
    path("", QuestionsListView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("hasker.users.urls", namespace="users"),
    ),
    path(
        "qa/",
        include("hasker.contrib.qa.urls", namespace="qa"),
    ),
    path("accounts/", include("allauth.urls")),
    path('api/v1/', include('hasker.api.urls', namespace='api_v1')),
    path('admin/', admin.site.urls),
    path('api-token-auth/', obtain_jwt_token, name='obtain_jwt_token'),
    path('api-token-verify/', verify_jwt_token, name='verify_jwt_token'),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

hasker/api/urls.py
from django.conf.urls import include, url
from django.urls import path
from rest_framework.routers import DefaultRouter
from rest_framework_swagger.views import get_swagger_view

from .viewsets import (
    QuestionAnswersApiView,
    QuestionApiView,
    QuestionListApiView,
    QuestionTrendingListApiView,
    SearchApiView,
    SearchByTagApiView
)

app_name = 'api_1'

schema_view = get_swagger_view(title='Hasker API (swagger)')
router = DefaultRouter()

urlpatterns = [
    url(r'^', include(router.urls)),
    path('questions/', QuestionListApiView.as_view(), name='questions'),
    path('questions/trending/', QuestionTrendingListApiView.as_view(), name='questions_trending'),
    path('questions/search/<str:query>/', SearchApiView.as_view(), name='questions_search'),
    path('questions/search/tag/<str:tag_name>/', SearchByTagApiView.as_view(), name='questions_search_by_tag'),
    path('questions/<slug:slug>/', QuestionApiView.as_view(), name='questions_details'),
    path('questions/<slug:slug>/answers/', QuestionAnswersApiView.as_view(), name='questions_answers'),
    path('docs/', schema_view),
]

hasker/contrib/qa/urls.py
from django.urls import path, register_converter

from .converters import NegativeIntConverter
from .views import (
    QuestionCorrectView,
    QuestionCreateView,
    QuestionDetails,
    RatingChangeView,
    SearchListView,
    answer_add,
    autocomplete_tags
)

register_converter(NegativeIntConverter, 'negint')

app_name = "qa"
urlpatterns = [
    path('add/', QuestionCreateView.as_view(), name='question-add'),
    path(
        'vote/<str:app_label>/<str:model_name>/<int:object_id>/<negint:action>/',
        RatingChangeView.as_view(), name='rating',
    ),
    path('search/', SearchListView.as_view(), name='search'),
    path('autocomplete/', autocomplete_tags, name='tags-autocomplete'),
    path('<int:id>/answer/add', answer_add, name='answer-add'),
    path('<slug:slug>/', QuestionDetails.as_view(), name='question-detail'),
    path('<int:question_id>-<int:answer_id>/correct/', QuestionCorrectView.as_view(), name='correct-answer'),
]

hasker/users/urls.py
from django.urls import path

from hasker.users.views import user_detail_view, user_list_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

hasker/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):

    avatar = models.ImageField('Логотип', upload_to='images/%Y/%m/', blank=True)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

hasker/contrib/qa/forms.py
from django.core.exceptions import ValidationError
from django.forms import CharField, ModelForm, TextInput

from .models import Answer, Question
from .widgets import TagsWidget


class QuestionCreateForm(ModelForm):
    tags = CharField(
        label='Теги', required=True, widget=TagsWidget,
        help_text='Минимум 1, Максимум 3',
    )
    title = CharField(widget=TextInput, label='Вопрос', max_length=200)

    def clean_tags(self):
        value = self.cleaned_data['tags']
        if not value:
            raise ValidationError('Укажите по крайне мере один тег')
        value = self.cleaned_data['tags'].split(',')

        # дополнительная защита, по умолчанию ограничение на уровне js widget-a
        if len(value) > 3:
            raise ValidationError('Не может быть более трех тегов')
        return value

    class Meta:
        model = Question
        fields = ('title', 'text', 'tags')


class AnswerCreateForm(ModelForm):

    class Meta:
        model = Answer
        fields = ('text',)

hasker/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django.forms import FileInput, ModelForm
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class ImageWidget(FileInput):
    """
    A ImageField Widget for admin that shows a thumbnail.
    Taken from https://djangosnippets.org/snippets/1580/
    """

    def render(self, name, value, attrs=None, **kwargs):
        output = []
        if value and hasattr(value, "url"):
            output.append(('<a target="_blank" href="%s">'
                           '<img src="%s" style="height: 250px;" /></a> <br /><br />'
                           % (value.url, value.url)))
        output.append(super().render(name, value, attrs))
        return mark_safe(u''.join(output))


class UserUpdateForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['username'].help_text = ''
        self.fields['avatar'].widget = ImageWidget()

    class Meta:
        model = User
        fields = ['username', 'email', 'avatar']

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']

        if avatar:
            try:
                w, h = get_image_dimensions(avatar)

                # validate dimensions
                max_width = max_height = 1000
                if w > max_width or h > max_height:
                    raise ValidationError(
                        'Please use an image that is '
                        '%s x %s pixels or smaller.' % (max_width, max_height),
                    )

                # validate content type
                main, sub = avatar.content_type.split('/')
                if not (main == 'image' and sub in ['jpeg', 'pjpeg', 'gif', 'png']):
                    raise ValidationError(
                        'Please use a JPEG, '
                        'GIF or PNG image.',
                    )

                # validate file size
                if len(avatar) > (200 * 1024):
                    raise ValidationError(
                        'Avatar file size may not exceed 200k.',
                    )

            except AttributeError:
                """
                Handles case when we are updating the user profile
                and do not supply a new avatar
                """
                pass

        return avatar


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")},
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

hasker/contrib/qa/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import SearchVector
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import Http404, HttpResponse, HttpResponseBadRequest, HttpResponseForbidden, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .forms import AnswerCreateForm, QuestionCreateForm
from .models import Answer, Question, Tag, Vote
from .tasks import sent_answer_add_notification


class QuestionsListView(ListView):
    model = Question
    paginate_by = 10
    template_name = 'pages/home.html'

    def get_queryset(self):
        qs = self.model.objects.filter(is_active=True).\
            prefetch_related('author', 'tags', 'correct_answer').\
            defer('text').annotate(Count('answer_set', distinct=True))
        try:
            sort = self.request.GET.get('sort_by')
            if sort == 'popular':
                qs = qs.order_by('-rating_sum', '-created_on')
        except Exception:
            pass
        return qs


class QuestionDetails(DetailView):
    model = Question
    template_name = 'qa/question_detail.html'

    def get_context_data(self, **kwargs):
        context = super(QuestionDetails, self).get_context_data(**kwargs)
        qs = self.object.answer_set.all().order_by('-rating_sum', '-created_on')
        p = Paginator(qs, 10)
        page = 1
        try:
            page_num = int(self.request.GET.get('page'))
            if page_num <= p.num_pages:
                page = page_num
        except Exception:
            pass

        context['answers'] = p.get_page(page)

        if self.request.user.is_authenticated:
            context['answer_form'] = AnswerCreateForm()
            context['is_author'] = self.request.user.pk == self.object.author.pk

        return context

    def get_object(self, queryset=None):
        obj = super(QuestionDetails, self).get_object(queryset)
        if not obj.is_active:
            raise Http404
        return obj


class QuestionCreateView(LoginRequiredMixin, CreateView):
    template_name = 'qa/question_create.html'
    form_class = QuestionCreateForm
    login_url = 'account_login'

    def form_valid(self, form):
        tags_list = form.cleaned_data['tags']
        question = form.save(commit=False)
        question.author = self.request.user
        question.is_active = True
        question.save()
        for tag in tags_list:
            tag, _ = Tag.objects.get_or_create(name=tag)
            question.tags.add(tag)

        messages.success(self.request, 'Ваш вопрос успешно добавлен.')
        return redirect('qa:question-detail', slug=question.slug)


class QuestionCorrectView(View):

    http_method_names = ['post']

    def post(self, request, question_id, answer_id, *args, **kwargs):
        question = get_object_or_404(Question, pk=question_id, author=request.user)
        question.update_correct_answer(answer_id)
        return redirect('qa:question-detail', slug=question.slug)


def autocomplete_tags(request):
    query = request.GET.get('q', '')
    qs = {}
    if query:
        qs = Tag.objects.filter(name__icontains=query).values('id', 'name')
    return JsonResponse(list(qs), safe=False)


@login_required
def answer_add(request, *args, **kwargs):
    question = get_object_or_404(Question, pk=kwargs.get('id'))
    answer = Answer(author=request.user, question=question)
    form = AnswerCreateForm(request.POST, instance=answer)
    if form.is_valid():
        form.save()
        sent_answer_add_notification.delay(answer.pk, question.pk)

    return redirect('qa:question-detail', slug=question.slug)


class RatingChangeView(View):
    http_method_names = ['post']

    def dispatch(self, request, *args, **kwargs):
        if not request.is_ajax():
            raise Http404
        return super(RatingChangeView, self).dispatch(request, *args, **kwargs)

    def post(self, request, app_label, model_name, object_id, action,  *args, **kwargs):
        try:
            if not request.user.is_authenticated:
                return HttpResponseForbidden('not authorized')

            # action only more or less
            if not Vote.is_valid_action_change_vote(action):
                return HttpResponseBadRequest('bad action')

            vote_value, rating = Vote.change_rating_action_vote(
                app_label,
                model_name,
                object_id,
                action,
                request.user,
            )
            response = {'status': 'ok', 'vote': vote_value, 'votes_all': rating}
            return HttpResponse(json.dumps(response))
        except ObjectDoesNotExist:
            return HttpResponseBadRequest('bad request')


class SearchListView(ListView):
    model = Question
    paginate_by = 10
    template_name = 'pages/search.html'

    def get_queryset(self):
        qs = self.model.objects.filter(is_active=True).\
            prefetch_related('author', 'tags', 'correct_answer').\
            defer('text')

        query = self.request.GET.get('search').strip()
        if not query or len(query) > 70:
            messages.error(self.request, 'Поисковый запрос не может быть пустым или более 70 символов')
            return Question.objects.none()

        if query and query.startswith('tag:'):
            query = query[4:]
            search_vector = SearchVector('tags__name',)
        else:
            search_vector = SearchVector('title', 'text')
        qs = qs.annotate(search=search_vector).filter(search=query)
        return qs

hasker/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .forms import UserUpdateForm

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    form_class = UserUpdateForm

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self, **kwargs):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

hasker/templates/qa/paginator.html
{% load questions_tags %}

{% if is_paginated %}
  <nav>
    <ul class="pagination pagination-sm justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">
            <span>&laquo;</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">
            <span>&laquo;</span>
          </a>
        </li>
      {% endif %}

      {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %}class="page-item active"{% endif %}>
          <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
        </li>
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">
            <span>&raquo;</span>
          </a>
        </li>
      {% else %}
        <li {% if not page_obj.has_next %}class="page-item disabled"{% endif %}>
          <a class="page-link" href="#">
            <span>&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

hasker/templates/qa/question_create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Задать впорос{% endblock %}

{% block content %}
  <h1>Задать впорос</h1>
  <form class="form-horizontal" method="post" action="{% url 'qa:question-add' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-dark btn-large">Задать</button>
      </div>
    </div>
  </form>
{% endblock %}

{% block bottom_js %}
  {{ form.media }}
{% endblock %}

hasker/templates/qa/question_detail.html
{% extends "base.html" %}

{% load questions_tags crispy_forms_tags %}

{% block content %}
  <div class="content">
    <h2 class="question__title-h">{{ object.title }}</h2>
    <div class="row question-wrap">
      <div class="col-1 text-center question__rating">
        {% rating object request.user %}
      </div>
      <div class="col-10 offset-1">
        <div class="question__text">{{ object.text }}</div>
        <div class="row">
          <div class="col-7">
            {% for tag in object.tags.all %}
              <a class="question__tag" href="{% url 'qa:search' %}?search=tag:{{ tag.name }}">
                <span>{{ tag.name }}</span>
              </a>
            {% endfor %}
          </div>
          <div class="col-5 text-right question__date">
            {{ question.created_on|time_ago }} от {{ question.author.username }}
          </div>
        </div>
      </div>
    </div>

    <div class="container answer">
      {% if question.answer_count %}
        <div class="answer__count">Ответов: {{ question.answer_count }}</div>
        {% for answer in answers %}
          <div class="row answer-wrap">
            <div class="col-1 text-center answer">
              {% rating answer request.user %}
            </div>
            <div class="col-1">
              <div class="question__true">
                {% if is_author %}
                  <form method="POST" action="{% url 'qa:correct-answer' question.pk answer.pk %}">
                    {% csrf_token %}
                    {% if answer.is_correct %}
                      <button type="submit" title="Правильный ответ"
                              class="correct-icon answer-button"></button>
                    {% else %}
                      <button type="submit" title="Отметить как правильный ответ"
                              class="not-correct-icon answer-button"></button>
                    {% endif %}
                  </form>
                {% elif answer.is_correct %}
                  <span title="Правильный ответ" class="correct-icon"></span>
                {% endif %}
              </div>
            </div>
            <div class="col-10">
              <div class="answer__text">{{ answer.text }}</div>
              <div class="text-right answer__date">
                {{ answer.created_on|time_ago }} от {{ answer.author.username }}
              </div>
            </div>
          </div>
        {% endfor %}
      {% else %}
        Пока что нет ответов
      {% endif %}

      {% if answers.paginator.num_pages > 1 %}
        <nav>
          <ul class="pagination pagination-sm justify-content-center">
            {% for page in answers.paginator.page_range %}
              <li {% if page == answers.number %}class="page-item active"{% endif %}>
                <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
              </li>
            {% endfor %}
          </ul>
        </nav>
      {% endif %}


    </div>
    {% if request.user.is_authenticated %}
      <div style="margin: 1rem 0;">
        <form action="{% url 'qa:answer-add' question.pk %}" method="post">
          {% csrf_token %}
          {{ answer_form|crispy }}
          <button type="submit" class="btn btn-dark btn-large">Ответить</button>
        </form>
      </div>
    {% else %}
      <div class="container">Авторизуйтесь (зарегистрируйтесь) для возможности добавить ответ.</div>
    {% endif %}
  </div>

{% endblock %}

{% block bottom_js %}
  <script>
    (function ($) {
      var $voteAction = $('.vote-action');
      var $votelink = $voteAction.find("a");
      $votelink.click(function (event) {
        event.preventDefault();
        var $thisLink = $(this);
        var $thisURL = $thisLink.attr('data-url');
        $.ajax({
          method: 'POST',
          beforeSend: function (request) {
            request.setRequestHeader("X-CSRFToken", jQuery("[name=csrfmiddlewaretoken]").val());
          },
          url: $thisURL,
          success: function (data) {
            handle_vote_action_success(data, $thisLink);
          },
          error: handle_vote_action_error
        })
      });

      function handle_vote_action_success(data, object) {
        var result = JSON.parse(data);
        var parent = object.parent('.vote-action');

        // set rating
        parent.find('span.ration-value').html(result.votes_all);
        // set icon
        switch (result.vote) {
          case -1:
            parent.find('.arrow-down').addClass('selected');
            parent.find('.arrow-up').removeClass('selected');
            break;
          case 0:
            parent.find('.arrow-down').removeClass('selected');
            parent.find('.arrow-up').removeClass('selected');
            break;

          case 1:
            parent.find('.arrow-down').removeClass('selected');
            parent.find('.arrow-up').addClass('selected');
            break;
        }
      }

      function handle_vote_action_error(jqXHR) {
        if (jqXHR.status === 403) {
          alert('Для того чтобы отправить голос необходимо авторизоваться')
        }
        else {
          alert('Произошла ошибка!!!')
        }
      }
    })($);
  </script>
{% endblock %}