config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token

from hasker.contrib.qa.views import QuestionsListView

urlpatterns = [
    path("", QuestionsListView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("hasker.users.urls", namespace="users"),
    ),
    path(
        "qa/",
        include("hasker.contrib.qa.urls", namespace="qa"),
    ),
    path("accounts/", include("allauth.urls")),
    path('api/v1/', include('hasker.api.urls', namespace='api_v1')),
    path('admin/', admin.site.urls),
    path('api-token-auth/', obtain_jwt_token, name='obtain_jwt_token'),
    path('api-token-verify/', verify_jwt_token, name='verify_jwt_token'),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT,
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

hasker/api/urls.py
from django.conf.urls import include, url
from django.urls import path
from rest_framework.routers import DefaultRouter
from rest_framework_swagger.views import get_swagger_view

from .viewsets import (
    QuestionAnswersApiView,
    QuestionApiView,
    QuestionListApiView,
    QuestionTrendingListApiView,
    SearchApiView,
    SearchByTagApiView
)

app_name = 'api_1'

schema_view = get_swagger_view(title='Hasker API (swagger)')
router = DefaultRouter()

urlpatterns = [
    url(r'^', include(router.urls)),
    path('questions/', QuestionListApiView.as_view(), name='questions'),
    path('questions/trending/', QuestionTrendingListApiView.as_view(), name='questions_trending'),
    path('questions/search/<str:query>/', SearchApiView.as_view(), name='questions_search'),
    path('questions/search/tag/<str:tag_name>/', SearchByTagApiView.as_view(), name='questions_search_by_tag'),
    path('questions/<slug:slug>/', QuestionApiView.as_view(), name='questions_details'),
    path('questions/<slug:slug>/answers/', QuestionAnswersApiView.as_view(), name='questions_answers'),
    path('docs/', schema_view),
]

hasker/contrib/qa/urls.py
from django.urls import path, register_converter

from .converters import NegativeIntConverter
from .views import (
    QuestionCorrectView,
    QuestionCreateView,
    QuestionDetails,
    RatingChangeView,
    SearchListView,
    answer_add,
    autocomplete_tags
)

register_converter(NegativeIntConverter, 'negint')

app_name = "qa"
urlpatterns = [
    path('add/', QuestionCreateView.as_view(), name='question-add'),
    path(
        'vote/<str:app_label>/<str:model_name>/<int:object_id>/<negint:action>/',
        RatingChangeView.as_view(), name='rating',
    ),
    path('search/', SearchListView.as_view(), name='search'),
    path('autocomplete/', autocomplete_tags, name='tags-autocomplete'),
    path('<int:id>/answer/add', answer_add, name='answer-add'),
    path('<slug:slug>/', QuestionDetails.as_view(), name='question-detail'),
    path('<int:question_id>-<int:answer_id>/correct/', QuestionCorrectView.as_view(), name='correct-answer'),
]

hasker/users/urls.py
from django.urls import path

from hasker.users.views import user_detail_view, user_list_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

hasker/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):

    avatar = models.ImageField('Логотип', upload_to='images/%Y/%m/', blank=True)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

hasker/contrib/qa/forms.py
from django.core.exceptions import ValidationError
from django.forms import CharField, ModelForm, TextInput

from .models import Answer, Question
from .widgets import TagsWidget


class QuestionCreateForm(ModelForm):
    tags = CharField(
        label='Теги', required=True, widget=TagsWidget,
        help_text='Минимум 1, Максимум 3',
    )
    title = CharField(widget=TextInput, label='Вопрос', max_length=200)

    def clean_tags(self):
        value = self.cleaned_data['tags']
        if not value:
            raise ValidationError('Укажите по крайне мере один тег')
        value = self.cleaned_data['tags'].split(',')

        # дополнительная защита, по умолчанию ограничение на уровне js widget-a
        if len(value) > 3:
            raise ValidationError('Не может быть более трех тегов')
        return value

    class Meta:
        model = Question
        fields = ('title', 'text', 'tags')


class AnswerCreateForm(ModelForm):

    class Meta:
        model = Answer
        fields = ('text',)

hasker/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions
from django.forms import FileInput, ModelForm
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class ImageWidget(FileInput):
    """
    A ImageField Widget for admin that shows a thumbnail.
    Taken from https://djangosnippets.org/snippets/1580/
    """

    def render(self, name, value, attrs=None, **kwargs):
        output = []
        if value and hasattr(value, "url"):
            output.append(('<a target="_blank" href="%s">'
                           '<img src="%s" style="height: 250px;" /></a> <br /><br />'
                           % (value.url, value.url)))
        output.append(super().render(name, value, attrs))
        return mark_safe(u''.join(output))


class UserUpdateForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['username'].help_text = ''
        self.fields['avatar'].widget = ImageWidget()

    class Meta:
        model = User
        fields = ['username', 'email', 'avatar']

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']

        if avatar:
            try:
                w, h = get_image_dimensions(avatar)

                # validate dimensions
                max_width = max_height = 1000
                if w > max_width or h > max_height:
                    raise ValidationError(
                        'Please use an image that is '
                        '%s x %s pixels or smaller.' % (max_width, max_height),
                    )

                # validate content type
                main, sub = avatar.content_type.split('/')
                if not (main == 'image' and sub in ['jpeg', 'pjpeg', 'gif', 'png']):
                    raise ValidationError(
                        'Please use a JPEG, '
                        'GIF or PNG image.',
                    )

                # validate file size
                if len(avatar) > (200 * 1024):
                    raise ValidationError(
                        'Avatar file size may not exceed 200k.',
                    )

            except AttributeError:
                """
                Handles case when we are updating the user profile
                and do not supply a new avatar
                """
                pass

        return avatar


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")},
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

hasker/contrib/qa/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import SearchVector
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import Http404, HttpResponse, HttpResponseBadRequest, HttpResponseForbidden, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .forms import AnswerCreateForm, QuestionCreateForm
from .models import Answer, Question, Tag, Vote
from .tasks import sent_answer_add_notification


class QuestionsListView(ListView):
    model = Question
    paginate_by = 10
    template_name = 'pages/home.html'

    def get_queryset(self):
        qs = self.model.objects.filter(is_active=True).\
            prefetch_related('author', 'tags', 'correct_answer').\
            defer('text').annotate(Count('answer_set', distinct=True))
        try:
            sort = self.request.GET.get('sort_by')
            if sort == 'popular':
                qs = qs.order_by('-rating_sum', '-created_on')
        except Exception:
            pass
        return qs


class QuestionDetails(DetailView):
    model = Question
    template_name = 'qa/question_detail.html'

    def get_context_data(self, **kwargs):
        context = super(QuestionDetails, self).get_context_data(**kwargs)
        qs = self.object.answer_set.all().order_by('-rating_sum', '-created_on')
        p = Paginator(qs, 10)
        page = 1
        try:
            page_num = int(self.request.GET.get('page'))
            if page_num <= p.num_pages:
                page = page_num
        except Exception:
            pass

        context['answers'] = p.get_page(page)

        if self.request.user.is_authenticated:
            context['answer_form'] = AnswerCreateForm()
            context['is_author'] = self.request.user.pk == self.object.author.pk

        return context

    def get_object(self, queryset=None):
        obj = super(QuestionDetails, self).get_object(queryset)
        if not obj.is_active:
            raise Http404
        return obj


class QuestionCreateView(LoginRequiredMixin, CreateView):
    template_name = 'qa/question_create.html'
    form_class = QuestionCreateForm
    login_url = 'account_login'

    def form_valid(self, form):
        tags_list = form.cleaned_data['tags']
        question = form.save(commit=False)
        question.author = self.request.user
        question.is_active = True
        question.save()
        for tag in tags_list:
            tag, _ = Tag.objects.get_or_create(name=tag)
            question.tags.add(tag)

        messages.success(self.request, 'Ваш вопрос успешно добавлен.')
        return redirect('qa:question-detail', slug=question.slug)


class QuestionCorrectView(View):

    http_method_names = ['post']

    def post(self, request, question_id, answer_id, *args, **kwargs):
        question = get_object_or_404(Question, pk=question_id, author=request.user)
        question.update_correct_answer(answer_id)
        return redirect('qa:question-detail', slug=question.slug)


def autocomplete_tags(request):
    query = request.GET.get('q', '')
    qs = {}
    if query:
        qs = Tag.objects.filter(name__icontains=query).values('id', 'name')
    return JsonResponse(list(qs), safe=False)


@login_required
def answer_add(request, *args, **kwargs):
    question = get_object_or_404(Question, pk=kwargs.get('id'))
    answer = Answer(author=request.user, question=question)
    form = AnswerCreateForm(request.POST, instance=answer)
    if form.is_valid():
        form.save()
        sent_answer_add_notification.delay(answer.pk, question.pk)

    return redirect('qa:question-detail', slug=question.slug)


class RatingChangeView(View):
    http_method_names = ['post']

    def dispatch(self, request, *args, **kwargs):
        if not request.is_ajax():
            raise Http404
        return super(RatingChangeView, self).dispatch(request, *args, **kwargs)

    def post(self, request, app_label, model_name, object_id, action,  *args, **kwargs):
        try:
            if not request.user.is_authenticated:
                return HttpResponseForbidden('not authorized')

            # action only more or less
            if not Vote.is_valid_action_change_vote(action):
                return HttpResponseBadRequest('bad action')

            vote_value, rating = Vote.change_rating_action_vote(
                app_label,
                model_name,
                object_id,
                action,
                request.user,
            )
            response = {'status': 'ok', 'vote': vote_value, 'votes_all': rating}
            return HttpResponse(json.dumps(response))
        except ObjectDoesNotExist:
            return HttpResponseBadRequest('bad request')


class SearchListView(ListView):
    model = Question
    paginate_by = 10
    template_name = 'pages/search.html'

    def get_queryset(self):
        qs = self.model.objects.filter(is_active=True).\
            prefetch_related('author', 'tags', 'correct_answer').\
            defer('text')

        query = self.request.GET.get('search').strip()
        if not query or len(query) > 70:
            messages.error(self.request, 'Поисковый запрос не может быть пустым или более 70 символов')
            return Question.objects.none()

        if query and query.startswith('tag:'):
            query = query[4:]
            search_vector = SearchVector('tags__name',)
        else:
            search_vector = SearchVector('title', 'text')
        qs = qs.annotate(search=search_vector).filter(search=query)
        return qs

hasker/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .forms import UserUpdateForm

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    form_class = UserUpdateForm

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self, **kwargs):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

hasker/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
  <h1>Forbidden (403)</h1>

  <p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

hasker/templates/base.html
{% load static questions_tags cache %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Hasker otus{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  {% block css %}
    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.min.css' %}" rel="stylesheet">
  {% endblock %}

</head>

<body>
  <div class="m-b-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
              data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="ml-3 navbar-brand mr-5 display-1" href="{% url 'home' %}">Хаскер</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form action="{% url 'qa:search' %}" method="GET" class="input-group my-2 mr-5 ml-5 my-lg-0">
          <input class="form-control" value="{{ request.GET.search }}" maxlength="70"
                 name="search" placeholder="Найти вопрос..." autocomplete="off"
                 autofocus="autofocus" type="text">
          <div class="input-group-btn">
            <button class="btn btn-outline-secondary" type="submit">Найти</button>
          </div>
        </form>
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link user-nav" href="{% url 'users:update' %}">
                {% if request.user.avatar %}
                <img src="{{ request.user.avatar.url }}" width="40">
                {% endif %}
                {{ request.user.username }}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link user-logout" href="{% url 'account_logout' %}">Выйти</a>
            </li>
          {% else %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">Зарегистрироваться</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">Войти</a>
            </li>
          {% endif %}
        </ul>
      </div>

    </nav>

  </div>
  <div class="container">
  <div class="row">
    <div class="col-9">
      <div class="container">
        {% if messages %}
          {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
        {% endif %}

        {% block content %}
          <p>Контент</p>
        {% endblock content %}

      </div> <!-- /container -->
    </div>
    <div class="col-3 text-center">
      <div class="container right-block">
        <div class="add-question">
          <a href="{% url 'qa:question-add' %}"
             class="btn btn-warning btn-block btn-large add-question__link">
            Задать вопрос
          </a>
        </div>
        {% cache 500 trending %}
          {% trending_questions %}
        {% endcache %}
      </div>
    </div>
  </div>
  </div>
  {% block modal %}{% endblock modal %}
  <!-- Le javascript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  {% block javascript %}
    <!-- Vendor dependencies bundled as one file-->
    <script src="{% static 'js/vendors.js' %}"></script>
    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/project.js' %}"></script>
  {% endblock javascript %}

  {% block bottom_js %}{% endblock %}

</body>
</html>